[versions]
androidGradlePlugin = "8.1.1"
kotlin = "1.9.10"
hilt = "2.48"
ksp = "1.9.10-1.0.13"

accompanist-permissions = "0.30.1"
activity-ktx = "1.7.2"
appcompat = "1.6.1"
composeBom = "2023.09.01"
core-ktx = "1.5.0"
datastore-preferences = "1.0.0"
guava = "32.1.2-android"
hilt-navigation-compose = "1.0.0"
jupiter = "5.10.0"
ktx = "1.12.0"
lifecycle = "2.6.2"
material = "1.9.0"
media = "1.6.0"
navigation-compose = "2.7.3"
preference-ktx = "1.2.1"
room = "2.5.2"
runner = "1.5.2"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "core-ktx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[bundles]
androidx-lifeycle = [
    "androidx-lifecycle-livedata-ktx",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
