name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SoundRemote
      uses: actions/checkout@v4

    - name: Checkout JOpus
      uses: actions/checkout@v4
      with:
        repository: ashipo/JOpus
        path: jopus

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build JOpus
      run: |
        cd jopus
        chmod +x ./gradlew
        ./gradlew --no-daemon lib:assembleRelease

    - name: Copy lib
      run: |
        mkdir app/libs
        cp -a jopus/lib/build/outputs/aar/lib-release.aar app/libs/

    - name: Build SoundRemote
      run: |
        chmod +x ./gradlew
        ./gradlew --no-daemon build
