name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SoundRemote
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build SoundRemote
      run: |
        chmod +x ./gradlew
        ./gradlew --no-daemon build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Release apk
        path: app/build/build/outputs/apk/release/*.apk
        retention-days: 3
