name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SoundRemote
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create keystore.jks
      env:
          KEYSTORE_JKS_BASE64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
      run: |
        echo $KEYSTORE_JKS_BASE64 | base64 --decode > "${{ github.workspace }}/keystore.jks"

    - name: Create keystore.properties
      env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      run: |
        echo -e "storeFile=${{ github.workspace }}/keystore.jks\nkeyAlias=$KEY_ALIAS\nkeyPassword=$KEY_PASSWORD\nstorePassword=$STORE_PASSWORD" > keystore.properties

    - name: Build SoundRemote
      run: |
        chmod +x ./gradlew
        ./gradlew --no-daemon build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-release
        path: app/build/outputs/apk/release/*.apk
